### ISSUE TITLE
Version 16 does not support JunitParams library

### ISSUE THREAD

**Issue by HardNorth** [sbabcoc/JUnit-Foundation#122]
Hello there.

I've tried to update our library on JUnit-Foundation version 16 and it look like it does not support JunitParams library anymore. All my tests related to this functionality fail. From what I can see no `testStarted` and `beforeInvocation` calls for such tests.

**Comment by sbabcoc** [comment]
Hmmm... The unit test collection includes a couple of JUnitParams tests, and they appear to run just fine. The big difference with release 16+ is that I replaced a bunch of reflective operations with byte code transformations. If any of the core JUnit classes get loaded prior to the execution of JUnit Foundation agent, these transformations will be disabled. I haven't been able to run `agent-java-junit` tests for a while, because I lost access to a Report Portal server to test against.

**Comment by sbabcoc** [comment]
Looking at the Gradle project for `agent-java-junit`, it looks like you're running with JUnit 5. This is incompatible with JUnit Foundation, which will only work with JUnit 4.

**Comment by sbabcoc** [comment]
I've been unable to import the project into Eclipse, so I can't do any debugging. I'm not well-versed in the ways of Gradle and don't have a clue how to fix the fundamental issues I'm running into.

**Comment by sbabcoc** [comment]
Found the issue, coded a fix, and published a new release.

**Comment by sbabcoc** [comment]
Resolved by #123
